name       : libseccomp
version    : 2.5.2
release    : 9
source     :
    - https://github.com/seccomp/libseccomp/releases/download/v2.5.2/libseccomp-2.5.2.tar.gz : 17a652dfb491d96be893960e9b791914936ee16c13b777a3caf562fe48cb87df
license    : LGPL-2.1-only
summary    : High level interface to the Linux Kernel's seccomp filter
component  : programming.library
description: |
    The libseccomp library provides an easy to use, platform independent, interface to the Linux Kernel's syscall filtering mechanism: seccomp. The libseccomp API is designed to abstract away the underlying BPF based syscall filter language and present a more conventional function-call based filtering interface that should be familiar to, and easily adopted by application developers.
builddeps  :
    - pkgconfig(valgrind)
    - gperf
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
