name       : libseccomp
version    : 2.2.3
release    : 1
source     :
    - https://github.com/seccomp/libseccomp/archive/v2.2.3.tar.gz : fee0a6671f160481dcd07760ea0df8b6d954bdd8b4ab20a423ac9ade5e4feced
license    : LGPL-2.0
summary    : High level interface to the Linux Kernel's seccomp filter
description: |
    The libseccomp library provides an easy to use, platform independent, interface to the Linux Kernel's syscall filtering mechanism: seccomp. The libseccomp API is designed to abstract away the underlying BPF based syscall filter language and present a more conventional function-call based filtering interface that should be familiar to, and easily adopted by application developers.
builddeps  :
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
