name       : libseccomp
version    : 2.5.4
release    : 11
source     :
    - https://github.com/seccomp/libseccomp/releases/download/v2.5.4/libseccomp-2.5.4.tar.gz : d82902400405cf0068574ef3dc1fe5f5926207543ba1ae6f8e7a1576351dcbdb
license    : LGPL-2.1-only
summary    : High level interface to the Linux Kernel's seccomp filter
component  : programming.library
description: |
    The libseccomp library provides an easy to use, platform independent, interface to the Linux Kernel's syscall filtering mechanism: seccomp. The libseccomp API is designed to abstract away the underlying BPF based syscall filter language and present a more conventional function-call based filtering interface that should be familiar to, and easily adopted by application developers.
builddeps  :
    - pkgconfig(valgrind)
    - gperf
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
